// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourWork2024.Models;

public partial class Brand
{
    [Key]
    public int ID { get; set; }

    [Required]
    public string Name { get; set; }

    public virtual ICollection<Model> Models { get; set; } = new List<Model>();
}