// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourWork2024.Models;


public partial class Car
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public int? ModelId { get; set; }

    public int? ColorId { get; set; }

    public int? BodyId { get; set; }

    public double mileage { get; set; }

    public DateTime FabDate { get; set; }

    public double Cost { get; set; }
    public int PictureId {  get; set; }

    public int? GearBoxId { get; set; }

    [ForeignKey("BodyId")]
    
    public virtual BodyType Body { get; set; }

    [ForeignKey("ColorId")]
 
    public virtual Color Color { get; set; }

    [ForeignKey("GearBoxId")]
    
    public virtual GearBox GearBox { get; set; }

    [ForeignKey("ModelId")]
    
    public virtual Model Model { get; set; }

    [ForeignKey(nameof(PictureId))]
    public Picture Picture {  get; set; }

    [ForeignKey("CarId")]
    
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}