// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourWork2024.Models;

public partial class Customer
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Customers")]
    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();
}