// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourWork2024.Models;

public partial class Model
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public int? BrandId { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("Models")]
    public virtual Brand Brand { get; set; }

   
    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();
}